###
GET http://localhost:3000/profile/
Authorization: Bearer JWT_TOKEN


###
GET http://localhost:3000/books/
Authorization: Bearer JWT_TOKEN
# Http Headers 
###

###
GET http://localhost:3000/books/4/
Authorization: Bearer JWT_TOKEN
###

GET http://localhost:3000/books/4/
Authorization: Bearer JWT_TOKEN



###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"vishal",
    "username":"vishal123",
    "password": "vishal@456",
    "gender": "Male",
    "location":"chandrapur"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"vishal123",
    "password": "vishal@456"
}